version: "3.8"
services:
  backend:
    image: "pecca86/springboot-react-fullstack:5.7.2022.9.1.47"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: "aws"
