version: "3.8"
services:
  backend:
    image: "pecca86/springboot-react-fullstack:10.7.2022.19.12.33"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: "aws"
