version: "3.8"
services:
  backend:
    image: "pecca86/springboot-react-fullstack:2.7.2022.10.29.44"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: "aws"
