name: CI

# on pull requests against main branch
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# Specify env variables
env:
  POSTGRESQL_VERSION: 14.3
  POSTGRESQL_DB: peccastudents
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  JAVA_VERSION: 17
  #JAVA_VERSION: 1.15

jobs:
  # Sequence of build steps to perform
  build:
    runs-on: ubuntu-latest
    # For connecting to a database
    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        # Check db health
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        node-version: [v16.13.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Maven Clean Package
        run: |
         cd fullstack/src/frontend && npm install
         cd ../../..
         cd fullstack
         cp -a src/frontend/build/ src/main/resources/static
         cd fullstack && ./mvnw --no-transfer-progress clean package
         cd ..

